# Generated by Django 5.0.1 on 2024-01-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lname',
        ),
    ]
