# Generated by Django 5.0.1 on 2024-01-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0004_admin_annee_filiere_teacher_user_user_type_matiere_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
