# Generated by Django 5.0.1 on 2024-01-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0006_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='DateSeance',
            field=models.DateField(auto_now=True),
        ),
    ]
