# Generated by Django 5.0.1 on 2024-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0009_filiere_identifiant_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='DateAttendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Identifiant_Matiere',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='Identifiant_professeur',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Identifiant_Attendance',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='Status',
            field=models.CharField(default='Absent(e)', max_length=20),
        ),
    ]
