# Generated by Django 5.0.1 on 2024-02-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0011_alter_attendance_identifiant_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='Nom',
            field=models.CharField(max_length=50),
        ),
    ]
