# Generated by Django 5.0.1 on 2024-03-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0012_alter_filiere_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='Identifiant_Annee',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pfe.annee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annee',
            name='Nom',
            field=models.CharField(max_length=50),
        ),
    ]
