# Generated by Django 5.0.1 on 2024-03-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0013_matiere_identifiant_annee_alter_annee_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='Identifiant_Annee',
        ),
    ]
