# Generated by Django 5.0.1 on 2024-03-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfe', '0014_remove_matiere_identifiant_annee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Identifiant_Annee',
        ),
    ]
